### ISSUE TITLE
How can I use a third party proxy  request address and a specified model?

### ISSUE THREAD

**Issue by cotagxrdhy** [GianfrancoCorrea/gpt-4-vision-chat#1]
How can I use a third party proxy  request address and a specified model?

**Comment by GianfrancoCorrea** [comment]
Hi @cotagxrdhy ! you are talking about replacing openai api with some proxy one? if that is the case you can use just python to make a request to the proxy.
Anyways i dont know why you need a proxy, i never implemented it, but if you explain me deeper, maybe i can help you 

If you want to change the model, you can do in the line 6 & 7.

**Comment by cotagxrdhy** [comment]
Hi @GianfrancoCorrea ,Yes, I want to replace "https://api.openai.com" with "https://api.daifuku.cloud". Can you please guide me through the specific steps to do so? Additionally, could you provide instructions on how to input the API Key? I apologize for my lack of proficiency in programming. Thank you once again for your response!

**Comment by GianfrancoCorrea** [comment]
@cotagxrdhy ok there is an easy way to do that. You can use "base_url" in the openai sdk. I made a change in the line [59 & 69](https://github.com/GianfrancoCorrea/gpt-4-vision-chat/blob/34e101e10718e565b1c3ebefe188fe7738399c2b/app.py#L59C41-L59C41). 
`client = OpenAI(base_url=os.environ["BASE_API_URL"])`

You just need to setup the enviorement, i created a file called [.env.example](https://github.com/GianfrancoCorrea/gpt-4-vision-chat/blob/34e101e10718e565b1c3ebefe188fe7738399c2b/.env.example), remove the .example and setup the API
```
OPENAI_API_KEY=openai-api-key # https://platform.openai.com/api-keys
BASE_API_URL=https://api.openai.com/v1
```

if you have troubles to set up the envirioment, you can set up the api key and the base url in the line [59 & 69](https://github.com/GianfrancoCorrea/gpt-4-vision-chat/blob/34e101e10718e565b1c3ebefe188fe7738399c2b/app.py#L59C41-L59C41).
`client = OpenAI(base_url="....", api_key="sk...")`

**Comment by cotagxrdhy** [comment]
Thank you so much!
