### ISSUE TITLE
Langsmith telemetry not working

### ISSUE THREAD

**Issue by ahsanshah** [GianfrancoCorrea/gpt-4-vision-chat#2]
I configured the env variables for Langsmith but it does not seem to send any information to Langsmith.  Is this properly configured in the app? Am unsure how to debug this.  I am able to make Langsmith work with standard langchain examples.

**Comment by GianfrancoCorrea** [comment]
Hi @ahsanshah, yes i removed that, it is not neccesary to make the chat work, but if you want to add it back, you can check the main file in the huggingface space: https://huggingface.co/spaces/DataPrism/GPT-4-Vision-Chat/blob/main/app.py

Or check the commit history :)
